### ISSUE TITLE
ignoring line because item ID is not valid

### ISSUE THREAD

**Issue by DOCTORdripp** [decentraland/l2-airdrop#5]
```
> l2-airdrop@0.0.0-development send
> ts-node -r dotenv/config ./src/send.ts "-c" "0xc494f4cdcf95de946a3e36d4cee7baf9c87f08de" "-i" "drip.csv"

ignoring line "0x000000000000000000000000000000000000dead,0" because item id is not valid
```

It's trying to say item 0 is not a valid ID number. 

What I've noticed is you can completely "forget" the collection address from the **npm run send** and it will deliver the same message. It's as if it can't validate the 0x collection.

I've replaced my address with the dead address to post this.

**Comment by 2fd** [comment]
Hi @DOCTORdripp , thanks for reporting this, should be fixed on the new release.
